/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 car.glb --transform 
Files: car.glb [28.42MB] > C:\Users\Universal\Documents\mufaddal\Z_OTHER\weddingexperience\wedding\public\models\car-transformed.glb [2.57MB] (91%)
Author: vecarz (https://sketchfab.com/heynic)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/blue-train-bentley-wwwvecarzcom-30aa29c6a50d41b19306c4fbd89d8e08
Title: Blue Train Bentley | www.vecarz.com
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Wheels} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Body} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Glow} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Details} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Bottom} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Interior} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Grid} />
    </group>
  )
}

useGLTF.preload('/car-transformed.glb')
