/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 woman.glb --transform 
Files: woman.glb [46.75MB] > C:\Users\Universal\Documents\mufaddal\Z_OTHER\weddingexperience\wedding\public\models\woman-transformed.glb [4.95MB] (89%)
Author: DENNISS75 (https://sketchfab.com/DENNISS75)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crimson-confidence-34f839ed82ff479fbd3b748d143c6d97
Title: Crimson Confidence
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/woman-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
    </group>
  )
}

useGLTF.preload('/woman-transformed.glb')
